version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - dotnet

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "02:30"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
